/*
 * Configuration.h
 *
 *  Created on: 15 abr. 2020
 *      Author: ziash
 */

#ifndef SRC_PLENLIBRARY_CONFIGURATION_H_
#define SRC_PLENLIBRARY_CONFIGURATION_H_

#define DEVICE_NAME "MiniPlen2"
#define CODE_NAME   "Conguito"
#define VERSION     "1.0"

#define NUMBER_OF_JOINTS 24

#define MOTION_FILE  		"/motion.bin"
#define MOTION_FILE_SIZE 	0x200000L

#define CONFIG_FILE  		"/joint_cfg.bin"
#define CONFIG_FILE_SIZE 	0x1000L

#define SYS_FILE  			"/sys_cfg.bin"
#define SYS_FILE_SIZE 		0x1000L

#define WIFI_PASSWORD 		"chocolate"
#define ACCESS_POINT_NAME 	"Conguito-"

#define DEFAULT_HTTP_PORT		 80
#define DEFAULT_WIFI_SOCKET_PORT 23

#define HOME_POSITION_LEFT_SHOULDER_PITCH 	-40
#define HOME_POSITION_LEFT_THIGH_YAW		254
#define HOME_POSITION_LEFT_SHOULDER_ROLL 	470
#define HOME_POSITION_LEFT_ELBOW_ROLL		-100
#define HOME_POSITION_LEFT_THIGH_ROLL		-205
#define HOME_POSITION_LEFT_THIGH_PITCH		50
#define HOME_POSITION_LEFT_KNEE_PITCH		445
#define HOME_POSITION_LEFT_FOOT_PITCH		245
#define HOME_POSITION_LEFT_FOOT_ROLL		-75
#define HOME_POSITION_RIGHT_SHOULDER_PITCH 	15
#define HOME_POSITION_RIGHT_THIGH_YAW		-70
#define HOME_POSITION_RIGHT_SHOULDER_ROLL	-390
#define HOME_POSITION_RIGHT_ELBOW_ROLL		250
#define HOME_POSITION_RIGHT_THIGH_ROLL		195
#define HOME_POSITION_RIGHT_THIGH_PITCH		-105
#define HOME_POSITION_RIGHT_KNEE_PITCH		-510
#define HOME_POSITION_RIGHT_FOOT_PITCH		-305
#define HOME_POSITION_RIGHT_FOOT_ROLL		60

#endif /* SRC_PLENLIBRARY_CONFIGURATION_H_ */
