/*
 * PinDefinition.h
 *
 *  Created on: 17 mar. 2020
 *      Author: Diego
 */

#ifndef SRC_PLENLIBRARY_PINDEFINITION_H_
#define SRC_PLENLIBRARY_PINDEFINITION_H_

#define PIN_LED	 16
#define PIN_EXPANSOR_ENABLE 13

#define PIN_LEFT_SHOULDER_PITCH 	1
#define PIN_LEFT_THIGH_YAW			2
#define PIN_LEFT_SHOULDER_ROLL 		3
#define PIN_LEFT_ELBOW_ROLL			4
#define PIN_LEFT_THIGH_ROLL			5
#define PIN_LEFT_THIGH_PITCH		6
#define PIN_LEFT_KNEE_PITCH			7
#define PIN_LEFT_FOOT_PITCH			8
#define PIN_LEFT_FOOT_ROLL			9
#define PIN_RIGHT_SHOULDER_PITCH 	10
#define PIN_RIGHT_THIGH_YAW			11
#define PIN_RIGHT_SHOULDER_ROLL		12
#define PIN_RIGHT_ELBOW_ROLL		14
#define PIN_RIGHT_THIGH_ROLL		14
#define PIN_RIGHT_THIGH_PITCH		15
#define PIN_RIGHT_KNEE_PITCH		16
#define PIN_RIGHT_FOOT_PITCH		17
#define PIN_RIGHT_FOOT_ROLL			18


#endif /* SRC_PLENLIBRARY_PINDEFINITION_H_ */
